### ISSUE TITLE
Handling endpoints

### ISSUE THREAD

**Issue by QSoto** [douma/laravel-database-routes#1]
I'm watching this package with some interest,
How should I handle the endpoints routes for AJAX calls?
I don't want to dynamic routing for endpoints.

Could I use api.php file?

**Comment by douma** [comment]
You can always fall back on laravel routing while using this package. This package is especially meant for having hundreds of dynamic routes existing at the same level (so /about-me, /contact going to different controllers). So if you have a few api routes you can always use the default laravel routing mechanism (use web.php or api.php and the Laravel route facade), they (the package & laravel default routes) run fine alongside.
