### ISSUE TITLE
Target class [ContactController::class] does not exist.

### ISSUE THREAD

**Issue by thuatnha** [douma/laravel-database-routes#3]
**My router** 

Douma\Routes\Routes\Route {#1637 ▼
  -url: "/contact"
  -isPattern: false
  -name: "contact"
  -controller: "ContactController::class" // tried with  ContactController
  -action: "index"
  -parameters: null
  -getParameters: null
}
**Error:**

Illuminate\Contracts\Container\BindingResolutionException
Target class [ContactController::class] does not exist.

Im user Larevel 7, php 7.2

**Comment by douma** [comment]
You should remove the quotes. Define a route like (without quotes at controller parameter):

```php 
use YourNamespace\ContactController; //top of php file 
new Route('/my-route',false, 'test1', ContactController::class, 'index'); //where you add the route
```

https://www.php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class
